const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
    STATE: 'STATE',
    UPDATE_AVATARIMG: 'UPDATE_AVATARIMG',
    UPDATE_COVERIMG: 'UPDATE_COVERIMG'
}


export default actionTypes