export { default as MainPage } from "./public/MainPage"
export { default as LandingPage } from "./public/LandingPage"
export { default as UserPage } from "./public/UserPage"
export { default as HomePage } from "./public/HomePage"
export { default as LoadingPage } from "./component/LoadingPage"
export { default as GroupPage} from "./public/GroupPage"